name: FFAplugin
version: 0.2
author: SkyZh0
main: me.skyzh0.FFAplugin.Main
description: This is an FFA plugin made by SkyZh0

commands:
  ffaleave:
    aliases: leave
    description: leave ffa event (in spec mode)
  lunchffa:
    aliases:
    description: lunch an ffa event !
  joinffa:
    aliases:
    description: join the ffa event :)
  ffaadmin:
    aliases: admin
    description: COOL ADMIN STUUF
api-version: 1.7.10